- HybridRemoteTemplate/bootconfig.json
As a result the start page chosen by user was not put into bootconfig.json
See https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/master/HybridRemoteTemplate/template.js#L49
> template.js is looking for HybridRemotePage not HybridRemoteTemplate

- ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
- iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj
The symlink was pointing to `node_modules`, it's now pointing to `mobile_sdk`. `iOSNative` and `iOSSwiftNative` are compiling and running now.
> Updating paths for image assets

- ReactNativeTemplate/ios/Podfile
- iOSNativeSwiftTemplate/Podfile
- iOSNativeTemplate/Podfile
See https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27
> Fix for xcode9/fmdb/sqlcipher/cocoapod issue

- iOSNativeSwiftTemplate/Podfile
Note: it compiles and runs but it's not yet using the new rest api wrappers
> Swift template now pulling in SalesforceSwiftSDK

- ReactNativeTemplate/android/app/build.gradle
- ReactNativeTemplate/android/gradle.properties
- ReactNativeTemplate/installandroid.js
- ReactNativeTemplate/package.json
- We need to explicitly override the value of `entryFile` in `react.gradle` -> it defaults to `index.android.js`, but we use a unified `index.js`.
- Removing the directories with rogue symlinks that break `assembleRelease` with `rimraf`.
> Fixing bug with assembleRelease

- ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
- iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m
Replace Commented code for SFLoginViewController customization. Moved code to use the following instead.
```
SFSDKLoginViewControllerConfig *loginViewConfig = [[SFSDKLoginViewControllerConfig  alloc] init];
loginViewConfig.showSettingsIcon = NO;
loginViewConfig.showNavbar = YES;
loginViewConfig.navBarColor = [UIColor redColor];
loginViewConfig.navBarTextColor = [UIColor whiteColor];
loginViewConfig.navBarFont = [UIFont boldSystemFontOfSize:20.0f];
[SFUserAccountManager sharedInstance].loginViewControllerConfig = loginViewConfig;
```
> Replace Commented code for SFLoginViewController customization

- ReactNativeTemplate/ios/Podfile
- ReactNativeTemplate/package.json
- SmartSyncExplorerReactNative/ios/Podfile
- SmartSyncExplorerReactNative/package.json
Both react native templates working fine. But you must use cocoapod 1.4.
(With 1.5 - it makes changes to the xcode project file which cause it not to build anymore)
> Move to 0.55.4

- SmartSyncExplorerSwift/Podfile
- iOSIDPTemplate/Podfile
- iOSNativeSwiftTemplate/Podfile
We do not need this dependency in the Podfile. It should be pulled transitively.
> Removing explicit PromiseKit dependency in Podfile

- BaristaSwift/Common/Common/Base/Store.swift
The application has a bunch of singletons (one per object type).
1) They were holding on to their SmartStore and SmartSync instances.
2) Soups and syncs were only setup at init time.
Now, we don't hold on to SmartStore or SmartSync instances and we setup soups and syncs on first access to store/sync manager following a logout.
NB: the app as it is would not support multiple users logged in
> Logout handling

- BaristaSwift/Consumer/Consumer/AppDelegate.swift
- ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
- SmartSyncExplorerSwift/SmartSyncExplorerSwift/AppDelegate.swift
- iOSIDPTemplate/Authenticator/AppDelegate.swift
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
- iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m
* No code is needed in AppDelegate
* handleAdvancedAuthenticationResponse renamed to handleIDPAuthenticationResponse
(Accompanies https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2621)
> Templates changes for SFAuthenticationSession

- ReactNativeTemplate/installios.js
- ReactNativeTemplate/ios/Podfile
- SmartSyncExplorerReactNative/installios.js
- SmartSyncExplorerReactNative/ios/Podfile
Related PRs:
- removal from main repo: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2657
- addition to React Native repo: https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/88
> Moving iOS React Native code and tests out of main repo

- ReactNativeTemplate/ios/Podfile
- SmartSyncExplorerReactNative/ios/Podfile
- SmartSyncExplorerReactNative/ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
- SmartSyncExplorerSwift/Podfile
- SmartSyncExplorerSwift/SmartSyncExplorerSwift.xcodeproj/project.pbxproj
- iOSIDPTemplate/Authenticator.xcodeproj/project.pbxproj
- iOSIDPTemplate/Podfile
- iOSNativeSwiftTemplate/Podfile
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
- iOSNativeTemplate/Podfile
- iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj
Similar change for all iOS templates. 
- Use the pod install hook to enable the flag across SDK
- Enable main preprocessor flag in sample app project. User other swift flags for swift projects.
> Added ability for templates to enable signposts

- ReactNativeTemplate/android/app/build.gradle
- ReactNativeTemplate/app.js
- ReactNativeTemplate/package.json
ReactNativeTemplate was using react-navigation@1.0.0-beta.11
Now it uses 2.18.3 (the last 2.x)
Notes:
- Didn't move to react-navigation 3.x because it depends in react-native-gesture-handler which doesn't work with Mobile SDK because we use AndroidX for compat libraries.
- RN 0.60 will bring AndroidX support and we can expect other libraries to support it as well.
- Working on SmartSyncExplorerReactNative next
> Using more (not most) recent react-navigation in ReactNativeTemplate

- ReactNativeTemplate/app.js
- SmartSyncExplorerReactNative/.babelrc
- SmartSyncExplorerReactNative/android/app/build.gradle
- SmartSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
- SmartSyncExplorerReactNative/android/gradle.properties
- SmartSyncExplorerReactNative/ios/Podfile
- SmartSyncExplorerReactNative/js/App.js
- SmartSyncExplorerReactNative/js/ContactScreen.js
- SmartSyncExplorerReactNative/js/Field.js
- SmartSyncExplorerReactNative/js/NavImgButton.js
- SmartSyncExplorerReactNative/js/SearchScreen.js
- SmartSyncExplorerReactNative/js/StoreMgr.js
- SmartSyncExplorerReactNative/js/Styles.js
- SmartSyncExplorerReactNative/package.json
- using react-navigation instead of navigation-experimental (nb: using react-navigation 2.x because react-navigation 3.x doesn't work with mobile sdk because of androidx)
- using FlatList instead of the deprecated ListView
- using `class xxx extends React.Component` instead of `createReactClass` for all components
-  moved styles to its own file (also cleaned them)
- moved NavImgButton class to its own file
- made some ui changes in detail screen (big save / small delete buttons as opposed to the opposite)
> Modernizing SmartSyncExplorerReactNative

- MobileSyncExplorerReactNative/package.json
This fixes Android release compilation for the MobileSyncExplorerReactNative project.
> Update RN Vector Icons version

- MobileSyncExplorerReactNative/ios/MobileSyncExplorerReactNative/AppDelegate.m
- MobileSyncExplorerSwift/MobileSyncExplorerSwift/AppDelegate.swift
- ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
- iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/AppDelegate.swift
- iOSIDPTemplate/Authenticator/AppDelegate.swift
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
- iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m
Instead of having lines and lines of commented out codes that we often forget to refactor whenever we make changes in the SDK, the example code now lives in small private methods. Only the calls to those privates methods are commented out.
> Limit commented out code

- iOSIDPTemplate/package.json
- setversion.sh
Was missing iOSIDPTemplate.
Only one of the two commits is needed.
The second one is better than the first IMHO.
> Fixing setversion.sh

- iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/SceneDelegate.swift
This fixes the issue related to faceid.  Subsequently to foregrounding the scene, the screen is activated and deactivated during the flow. It's best to perform the loginIfRequired only when the scene is foregrounded.
> Move LoginIfRequired to Scene's didEnterForeground

- MobileSyncExplorerReactNative/android/settings.gradle
- MobileSyncExplorerReactNative/ios/MobileSyncExplorerReactNative.xcodeproj/project.pbxproj
- MobileSyncExplorerReactNative/ios/Podfile
- MobileSyncExplorerReactNative/js/App.js
- MobileSyncExplorerReactNative/js/ContactScreen.js
- MobileSyncExplorerReactNative/js/SearchScreen.js
- MobileSyncExplorerReactNative/package.json
- ReactNativeTemplate/android/settings.gradle
- ReactNativeTemplate/app.js
- ReactNativeTemplate/ios/Podfile
- ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
- ReactNativeTemplate/package.json
We were using an old version of react navigation (2.18), so I moved to the latest react navigation (5.2). The js changes are for the new navigation.
> Moving to React Native 0.62.2

- MobileSyncExplorerReactNative/js/SearchScreen.js
- MobileSyncExplorerReactNative/js/StoreMgr.js
Behavior before fix:
If you have many contacts and search for abcd (typing the letters quickly), a search is fired for a, then for ab, then for abc, and finally for abcd. Naturally, the search for abcd ends first, followed by the search for abc, the one for ab and the one for a. So you will end up with the results for a (and the "a" in the search box).
Behavior with fix:
Only results for the most recent search should be shown, other results should be discarded without changing the state of the screen.
> Bug fix: search screen should show results for most recently typed query

- HybridLwcTemplate/server/force-app/main/default/lwc/contactListItem/contactListItem.html
Like the other basic template, we only show a list of contacts, we don't have a detail screen.
Before this change, clicking on a list item would cause the whole screen to re-render (and a few times it went blank).
> Disabling link on contact list item

- ReactNativeTypeScriptTemplate/template.js
The actual path contains the app name in all lowercase but the path being technically wrong only affects Linux.  I believe this is due to how the filesystem handles paths at a low level and it appears OSX is case insensitive while linux is case sensitive.  So the same `fs.readfilesync` call will fail on one but not the other.
> Fix ReactNativeTypeScriptTemplate issue on Linux systems.

- MobileSyncExplorerReactNative/ios/Podfile
- ReactNativeDeferredTemplate/ios/Podfile
- ReactNativeTemplate/ios/Podfile
- ReactNativeTypeScriptTemplate/ios/Podfile
With this change, forcereact generated apps will auto-link their dependencies.
Mobile SDK dependencies are still brought in "manually".
Auto-linking mobile sdk is of limited value because the app needs certain things in the native side of the project (e.g. AppDelegate, bootconfig) which are best brought in by using forcereact to generate the app.
> Simplifying pod files for RN templates

- AndroidIDPTemplate/app/build.gradle
- AndroidIDPTemplate/build.gradle
- AndroidIDPTemplate/gradle/wrapper/gradle-wrapper.properties
- AndroidNativeKotlinTemplate/app/build.gradle
- AndroidNativeKotlinTemplate/build.gradle
- AndroidNativeKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
- AndroidNativeTemplate/app/build.gradle
- AndroidNativeTemplate/build.gradle
- AndroidNativeTemplate/gradle/wrapper/gradle-wrapper.properties
- MobileSyncExplorerReactNative/android/app/build.gradle
- MobileSyncExplorerReactNative/android/build.gradle
- MobileSyncExplorerReactNative/android/gradle/wrapper/gradle-wrapper.properties
- ReactNativeDeferredTemplate/android/app/build.gradle
- ReactNativeDeferredTemplate/android/build.gradle
- ReactNativeDeferredTemplate/android/gradle/wrapper/gradle-wrapper.properties
- ReactNativeTemplate/android/app/build.gradle
- ReactNativeTemplate/android/build.gradle
- ReactNativeTemplate/android/gradle/wrapper/gradle-wrapper.properties
- ReactNativeTypeScriptTemplate/android/app/build.gradle
- ReactNativeTypeScriptTemplate/android/build.gradle
- ReactNativeTypeScriptTemplate/android/gradle/wrapper/gradle-wrapper.properties
- Upgrading to `AGP 4.2` for `Android Studio 4.2`.
- Upgrading to `Kotlin 1.5`.
- Removing `jcenter()` from most places, except where it's required for `PaperDB`.
- Replacing `api` with `implementation`.
> Cleaning up and Upgrading Android Templates

- MobileSyncExplorerReactNative/package.json
- ReactNativeDeferredTemplate/package.json
- ReactNativeTemplate/package.json
- ReactNativeTypeScriptTemplate/package.json
This is fixes a crash for Android release builds.
> Bump React Native to 0.67.1.

- MobileSyncExplorerReactNative/ios/MobileSyncExplorerReactNative.xcodeproj/project.pbxproj
- MobileSyncExplorerReactNative/ios/Podfile
- ReactNativeDeferredTemplate/ios/Podfile
- ReactNativeDeferredTemplate/ios/ReactNativeDeferredTemplate.xcodeproj/project.pbxproj
- ReactNativeTemplate/ios/Podfile
- ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
- ReactNativeTypeScriptTemplate/ios/Podfile
- ReactNativeTypeScriptTemplate/ios/ReactNativeTypeScriptTemplate.xcodeproj/project.pbxproj
- no longer using use_frameworks!
- calling helper functions defined in mobilesdk_pods.rb
- now it works with Hermes enabled
(however it still failing to build with Xcode 13 / it works fine with Xcode 14)
> Cleaner pod files for React Native templates

- MobileSyncExplorerSwift/Podfile
- iOSIDPTemplate/Podfile
- iOSNativeSwiftEncryptedNotificationTemplate/Podfile
- iOSNativeSwiftTemplate/Podfile
- iOSNativeTemplate/Podfile
Calling mobile_sdk_post_install which fixes deployment targets (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3601)
> Fix for Xcode 14.3

- AndroidIDPTemplate/app/AndroidManifest.xml
- AndroidIDPTemplate/app/build.gradle
- AndroidIDPTemplate/template.js
- AndroidNativeKotlinTemplate/app/AndroidManifest.xml
- AndroidNativeKotlinTemplate/app/build.gradle
- AndroidNativeKotlinTemplate/template.js
- AndroidNativeTemplate/app/AndroidManifest.xml
- AndroidNativeTemplate/app/build.gradle
- AndroidNativeTemplate/package.json
- AndroidNativeTemplate/template.js
- MobileSyncExplorerKotlinTemplate/app/AndroidManifest.xml
- MobileSyncExplorerKotlinTemplate/app/build.gradle
- MobileSyncExplorerKotlinTemplate/template.js
- MobileSyncExplorerReactNative/android/app/build.gradle
- MobileSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
- MobileSyncExplorerReactNative/template.js
- ReactNativeDeferredTemplate/android/app/build.gradle
- ReactNativeDeferredTemplate/android/app/src/main/AndroidManifest.xml
- ReactNativeDeferredTemplate/template.js
- ReactNativeTemplate/android/app/build.gradle
- ReactNativeTemplate/android/app/src/main/AndroidManifest.xml
- ReactNativeTemplate/template.js
- ReactNativeTypeScriptTemplate/android/app/build.gradle
- ReactNativeTypeScriptTemplate/android/app/src/main/AndroidManifest.xml
- ReactNativeTypeScriptTemplate/template.js
Addressing deprecation message during builds:
> package="com.salesforce.androidsdk" found in source AndroidManifest.xml: /home/circleci/SalesforceMobileSDK-Package/tmp20230608T035347.445/androidnativekotlin/mobile_sdk/SalesforceMobileSDK-Android/libs/SalesforceSDK/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https://developer.android.com/studio/build/configure-app-module#set-namespace
> Moving package name to build.gradle

- MobileSyncExplorerKotlinTemplate/app/AndroidManifest.xml
In the past template.js was replacing the template package name by the user provided package name in AndroidManifest.xml, so having the full package name in there was not a problem.
With https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/360, I moved the package name to build.gradle and modified template.js to no touch AndroidManifest.xml.
> Not having full package name in AndroidManifest.xml

- MobileSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
- MobileSyncExplorerReactNative/template.js
- ReactNativeDeferredTemplate/android/app/src/main/AndroidManifest.xml
- ReactNativeDeferredTemplate/template.js
- ReactNativeTemplate/android/app/src/main/AndroidManifest.xml
- ReactNativeTemplate/template.js
- ReactNativeTypeScriptTemplate/android/app/src/main/AndroidManifest.xml
- ReactNativeTypeScriptTemplate/template.js
On iOS, our Podfile has
- config = use_native_modules!
- Which comes from node_modules/@react-native-community/cli-platform-ios/native_modules 
- Which calls node_modules/@react-native-community/cli/build/bin.js
On Android, our build.gradle has
- apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle") 
- Which also calls node_modules/@react-native-community/cli/build/bin.js
bin.js is the one complaining about not finding a package name in the AndroidManifest.xml
> Removing the package name from AndroidManifest.xml broke RN for Android and iOS

- MobileSyncExplorerReactNative/package.json
- ReactNativeDeferredTemplate/package.json
- ReactNativeTemplate/package.json
- ReactNativeTypeScriptTemplate/package.json
🎸 _Ready For Review_ 🥁
This corrects a few remaining placeholder versions in the template `package.json` files from `setVersion.sh` testing.  Thanks, @wmathurin 🦅
> @W-14246983: [MSDK Android Templates] Templates Use Maven Central MSDK Dependencies By Default (Pt. 2)

- HybridLocalTemplate/template.js
- HybridLwcTemplate/template.js
- HybridRemoteTemplate/template.js
Without this check if you build an hybrid app only for iOS it fails because it can't find the Android directory it is looking for.
> Fix iOS hybrid generation.

- AndroidIDPTemplate/app/build.gradle.kts
- AndroidNativeKotlinTemplate/app/build.gradle.kts
- AndroidNativeTemplate/app/build.gradle.kts
- MobileSyncExplorerKotlinTemplate/app/build.gradle.kts
- MobileSyncExplorerReactNative/android/build.gradle
- ReactNativeDeferredTemplate/android/build.gradle
- ReactNativeTemplate/android/build.gradle
- ReactNativeTypeScriptTemplate/android/build.gradle
Also removing target sdk
> The targetSdk property in the Android library Gradle plugin ("com.android.library") has been deprecated. As it is an advisory property, you can safely remove it from your configuration. The minSdk property alone is sufficient.
> Changing min sdk from 24 to 26

- iOSNativeLoginTemplate/iOSNativeLoginTemplate/NativeLoginViewFactory.swift
- iOSNativeLoginTemplate/iOSNativeLoginTemplate/SceneDelegate.swift
🎸 _Ready For Review_ 🥁 
This is a simple follow-up to https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/395 to (again) revert the native login properties to the template values.  This was correct, but looks to have been accidentally set back during a code review commit.
> @W-14584260: [iOS] OTPs Sample App (Correct Template Properties)

- MobileSyncExplorerReactNative/package.json
- ReactNativeDeferredTemplate/package.json
- ReactNativeTemplate/package.json
- ReactNativeTypeScriptTemplate/package.json
On CI getting this error
> Execution failed for task ':react-native-screens:configureCMakeDebug[arm64-v8a]'.
So moving to most recent version of react-native-screens.
Some of the recent updates have release notes about supporting React Native 0.73.
> Moving to most recent react-native-screens

- AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/MainApplication.kt
- AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/NativeLogin.kt
- iOSNativeLoginTemplate/iOSNativeLoginTemplate/NativeLoginView.swift
- iOSNativeLoginTemplate/iOSNativeLoginTemplate/NativeLoginViewFactory.swift
- iOSNativeLoginTemplate/iOSNativeLoginTemplate/SceneDelegate.swift
Because it is very easy to find and replace strings in the UI Testing framework (like `your-client-id`) but difficult to add full LOC from scratch at specific places in file I have made username / password login the default flow.  It is impossible to UI Test Password-less login so its setup, that would otherwise cause the app to not compile, is commented out. 
UI Testing PR: https://github.com/forcedotcom/SalesforceMobileSDK-UITests/pull/39
> Setup Native Login for UI testing.

- AndroidNativeLoginTemplate/settings.gradle.kts
- iOSNativeLoginTemplate/iOSNativeLoginTemplate/NativeLoginView.swift
🤘🏻 _*Ready For Review!_ 🎤
This is a companion to the MSDK implementation in https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3728
The most interesting part of the code is a handful of utility methods in the layout to help keep the code from being repetitive.
Here are a few useful screenshots.
> @W-15316962/W-15316987: [iOS] Update native login sample app to include User Registration/Forgot Password flows

- AndroidNativeKotlinTemplate/app/src/main/AndroidManifest.xml
- AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/MainActivity.kt
- AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/MainApplication.kt
- AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/QrCodeEnabledLoginActivity.kt
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/LoginTypeSelectionViewController.swift
- iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/SceneDelegate.swift
🤘🏻 _*Ready For Review!*_ 🎸
This is a parallel to https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/426.  The key change for the template is updating the naming conventions, documentation and a few customization options to match the public API for QR Code Log In we just finished for Android.
Thanks, as always, for reading along ⭐️
> @W-16814802: [iOS] Add Deep Link From External QR Code Reader To iOS Native Swift Template QR Code Login

- MobileSyncExplorerSwift/MobileSyncExplorerSwift/SObjects/Contacts.swift
- MobileSyncExplorerSwift/MobileSyncExplorerSwift/UI/ContactList/ContactList.swift
Contacts in list were not showing correct local status:
- edit -> list -> sync would still show contact as locally edited
- delete -> list would not show contact as locally deleted
The problem was that the == method on ContactSObject did not compare locally created/updated or deleted fields
> Fixing issues in MobileSyncExplorerSwift

- ReactNativeDeferredTemplate/android/app/src/main/java/com/salesforce/reactnativedeferredtemplate/MainActivity.java
- ReactNativeTemplate/android/app/src/main/java/com/salesforce/reactnativetemplate/MainActivity.java
- ReactNativeTypeScriptTemplate/android/app/src/main/java/com/salesforce/reactnativetypescripttemplate/MainActivity.java
This was already done for the Android MobileSync React Native template with #432, but I discovered today it is needed for all templates.  
No need to patch or anything since this only affects debug builds.
> Fix React Native Android First Time Login Crash.

- MobileSyncExplorerReactNative/ios/MobileSyncExplorerReactNative/AppDelegate.m
- ReactNativeDeferredTemplate/ios/ReactNativeDeferredTemplate/AppDelegate.m
- ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
- ReactNativeTypeScriptTemplate/ios/ReactNativeTypeScriptTemplate/AppDelegate.m
- iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m
- iOSNativeTemplate/iOSNativeTemplate/RootViewController.h
- iOSNativeTemplate/iOSNativeTemplate/RootViewController.m
This update modernizes Salesforce SDK header inclusion in all iOS template projects by replacing multiple #import statements with a single @import SalesforceSDKCore.
= Replace #import <SalesforceSDKCore/…> headers with @import SalesforceSDKCore; in the following templates:
•	MobileSyncExplorerReactNative
•	ReactNativeDeferredTemplate
•	ReactNativeTemplate
•	ReactNativeTypeScriptTemplate
•	iOSNativeTemplate
•	Replaced #import <SalesforceSDKCore/SFRestAPI.h> in RootViewController.h with @import SalesforceSDKCore.
Benefits
•	Reduces boilerplate and potential import conflicts
•	Aligns with modern Objective-C best practices for module imports
•	Improves maintainability and consistency across all templates
Notes
Ensure that CLANG_ENABLE_MODULES = YES is set in Xcode build settings if not …
> @W-18598929 Migrate Salesforce SDK imports to use @import directive

- AndroidIDPTemplate/app/build.gradle.kts
- AndroidIDPTemplate/build.gradle.kts
- AndroidIDPTemplate/buildSrc/build.gradle.kts
- AndroidIDPTemplate/gradle/wrapper/gradle-wrapper.properties
- AndroidNativeKotlinTemplate/app/build.gradle.kts
- AndroidNativeKotlinTemplate/build.gradle.kts
- AndroidNativeKotlinTemplate/buildSrc/build.gradle.kts
- AndroidNativeKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
- AndroidNativeLoginTemplate/app/build.gradle.kts
- AndroidNativeLoginTemplate/build.gradle.kts
- AndroidNativeLoginTemplate/buildSrc/build.gradle.kts
- AndroidNativeLoginTemplate/gradle/wrapper/gradle-wrapper.properties
- AndroidNativeTemplate/app/build.gradle.kts
- AndroidNativeTemplate/build.gradle.kts
- AndroidNativeTemplate/buildSrc/build.gradle.kts
- AndroidNativeTemplate/gradle/wrapper/gradle-wrapper.properties
- MobileSyncExplorerKotlinTemplate/app/build.gradle.kts
- MobileSyncExplorerKotlinTemplate/build.gradle.kts
- MobileSyncExplorerKotlinTemplate/buildSrc/build.gradle.kts
- MobileSyncExplorerKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
- MobileSyncExplorerReactNative/android/build.gradle
- MobileSyncExplorerReactNative/android/gradle/wrapper/gradle-wrapper.properties
- ReactNativeDeferredTemplate/android/build.gradle
- ReactNativeDeferredTemplate/android/gradle/wrapper/gradle-wrapper.properties
- ReactNativeTemplate/android/build.gradle
- ReactNativeTemplate/android/gradle/wrapper/gradle-wrapper.properties
- ReactNativeTypeScriptTemplate/android/build.gradle
- ReactNativeTypeScriptTemplate/android/gradle/wrapper/gradle-wrapper.properties
🎸 _*Ready For Review!*_ 🥁
This updates all the MSDK Android Templates to the latest Gradle and Android Gradle Plugin plus a few other dependency updates.  However, it doesn't take the next two steps of updating to Kotlin 2 and the Kotlin Compose Compiler Gradle Plugin or Android API 36.
Note: There are two really valuable "future" commits on this branch history that actually have working code for the two deferred steps.  We can cherry pick those in when the time comes for some serious effort reduction since that's completed.
> @W-18648586: Gradle upgrade
