ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m

Added comments for handling Advanced Auth flow.

Added comments for handling Advanced Auth flow

---

ReactNativeTemplate/index.android.js
ReactNativeTemplate/package.json

Navigator is deprecated, so rewrote template application using StackNavigator. Also switched from ListView to FlatList.

Updating android react native template for react native 0.45.1

---

.gitignore
AndroidNativeTemplate/install.js
AndroidNativeTemplate/package.json
AndroidNativeTemplate/settings.gradle
ReactNativeTemplate/android/settings.gradle
ReactNativeTemplate/installandroid.js
ReactNativeTemplate/installios.js
ReactNativeTemplate/ios/Podfile
ReactNativeTemplate/package.json
iOSNativeSwiftTemplate/Podfile
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
iOSNativeSwiftTemplate/install.js
iOSNativeSwiftTemplate/package.json
iOSNativeTemplate/Podfile
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj
iOSNativeTemplate/install.js
iOSNativeTemplate/package.json

Using a shallow git clone instead of npm dependencies (which were also getting submodules)

Speeding up SDK dependencies download

---

ReactNativeTemplate/app.js
ReactNativeTemplate/package.json

Fixes for react native templates

---

ReactNativeTemplate/ios/Podfile
iOSNativeSwiftTemplate/Podfile
iOSNativeTemplate/Podfile

However because of the XCode 9 issue, getting it from branch 2.7.2_xcode9 on our fork (which has 2.7.2 + import fix for xcode 9)

FMDB is now coming from cocoapods

---

HybridLocalTemplate/install.js
HybridLocalTemplate/package.json
HybridLocalTemplate/template.js
HybridRemoteTemplate/install.js
HybridRemoteTemplate/package.json
HybridRemoteTemplate/template.js
ReactNativeTemplate/installios.js
iOSNativeTemplate/install.js

We already made those changes to the other templates (in Mobile SDK 5.2).
npm 5 does not download http dependencies, so you end up missing force.js.

Changes to hybrid template so they work with npm 5

---

AndroidNativeKotlinTemplate/app/AndroidManifest.xml
AndroidNativeKotlinTemplate/gradle.properties
AndroidNativeTemplate/app/AndroidManifest.xml
AndroidNativeTemplate/gradle.properties
ReactNativeTemplate/android/app/build.gradle
ReactNativeTemplate/android/app/src/main/AndroidManifest.xml

Forgot to revert min api bump in https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/65

Code for 5.3 (part 2)

---

iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj

NB: no code change were required - only project settings were updated

Swift template now uses Swift 4

---

ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m

Changed commented code in  templates to use SFUserAccountManager instead of SFAuthenticationManager

Changing templates to use SFUserAccountManager

---

ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj

Fixing Xcode compatibility versions

---

iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift

Goes with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2322

Setting instance class of SDK manager to (new) SalesforceSDKSwiftManager

---

AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainActivity.kt
AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainApplication.kt
iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m

Switching to SmartSyncSDKManager by default

---

ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj

All templates are compiling and running now with `Xcode 9.2`.

Updating project files to recommended settings

---

AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainApplication.kt
AndroidNativeTemplate/app/src/com/salesforce/androidnativetemplate/MainApplication.java
ReactNativeTemplate/android/app/src/main/java/com/salesforce/reactnativetemplate/MainApplication.java

Removing the static way of enforcing browser-based auth.

Removing unapplicable code from templates

---

SmartSyncExplorerReactNative/js/App.js
SmartSyncExplorerReactNative/js/ContactScreen.js

Instead of being next to "Save" button.
Now the same as native SmartStoreExplorer apps.

Better usability: delete/undelete button below fields

---

SmartSyncExplorerReactNative/js/App.js

Now the same as the native SmartSyncExplorer apps.

Confirmation popup when clicking logout nav button

---

SmartSyncExplorerSwift/SmartSyncExplorerSwift/ViewControllers/AdditionalActionsViewController.swift
SmartSyncExplorerSwift/SmartSyncExplorerSwift/ViewControllers/RootViewController.swift

Added ability to return from settings view

Added ability to return from settings view

---

ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m

Automatic login in ReacNativeTemplate on iOS

---

SmartSyncExplorerReactNative/js/StoreMgr.js

* Using promiserNoRejection for sync operations to gracefully handle errors while offline
* Going to the end of the result set when querying smartstore (before we were just getting first 100)

Using promises in StoreMgr

---

SmartSyncExplorerReactNative/js/App.js
SmartSyncExplorerReactNative/js/ContactCell.js
SmartSyncExplorerReactNative/js/ContactScreen.js
SmartSyncExplorerReactNative/js/StoreMgr.js

If record fail to sync, the sync-problem icon is shown in the list and the error message is shown in the detail screen.
Changing the record removes the last error.

Showing last error if any

---

BaristaSwift/Common/Common/Base/Store.swift

Creating sync down and sync up for each object type at the beginning.
Then simply calling reSync(byName:syncName).
(It will do a full sync the first time and then only delta syncs).

Not creating sync down/up with every call

---

BaristaSwift/Common/Common/Base/Store.swift
BaristaSwift/Common/Common/Store/AccountStore.swift
BaristaSwift/Common/Common/Store/FavoritesStore.swift
BaristaSwift/Common/Common/Store/OpportunityStore.swift
BaristaSwift/Common/Common/Store/OrderItemStore.swift
BaristaSwift/Common/Common/Store/OrderStore.swift
BaristaSwift/Common/Common/Store/PricebookStore.swift
BaristaSwift/Common/Common/Store/ProductOptionStore.swift
BaristaSwift/Common/Common/Store/ProductStore.swift
BaristaSwift/Common/Common/Store/QuoteLineGroupStore.swift
BaristaSwift/Common/Common/Store/QuoteLineItemStore.swift
BaristaSwift/Common/Common/Store/QuoteStore.swift
BaristaSwift/Common/Common/Store/UserStore.swift

Added runQuery method to Store.swift. All SmartStore queries of the apps are run through it.

Timing syncs and queries

---

AndroidIDPTemplate/app/build.gradle
AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainApplication.kt
AndroidIDPTemplate/build.gradle
AndroidNativeKotlinTemplate/app/build.gradle
AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainActivity.kt
AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainApplication.kt
AndroidNativeKotlinTemplate/build.gradle
AndroidNativeTemplate/app/src/com/salesforce/androidnativetemplate/MainActivity.java
AndroidNativeTemplate/app/src/com/salesforce/androidnativetemplate/MainApplication.java
ReactNativeTemplate/android/app/build.gradle
ReactNativeTemplate/android/app/src/main/java/com/salesforce/reactnativetemplate/MainApplication.java
SmartSyncExplorerReactNative/android/app/build.gradle

This updates the templates to accommodate the latest changes from `dev`.

Fixing Android templates

---

BaristaSwift/Common/Common/Base/Store.swift
BaristaSwift/Common/Common/Store/ProductOptionStore.swift
BaristaSwift/Consumer/Consumer/ViewController/ProductViewController.swift

Adding timing to the count query.
Fixing misc compilation warnings.

Misc fixes

---

BaristaSwift/Consumer/Consumer.xcodeproj/project.pbxproj
BaristaSwift/Consumer/Consumer/AppDelegate.swift
BaristaSwift/Consumer/Consumer/Resource/bootconfig.plist
BaristaSwift/Provider/Provider.xcodeproj/project.pbxproj
BaristaSwift/Provider/Provider/AppDelegate.swift
BaristaSwift/Provider/Provider/Resource/bootconfig.plist
ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m
ReactNativeTemplate/ios/ReactNativeTemplate/bootconfig.plist
SmartSyncExplorerReactNative/ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
SmartSyncExplorerReactNative/ios/SmartSyncExplorerReactNative/AppDelegate.m
SmartSyncExplorerReactNative/ios/SmartSyncExplorerReactNative/bootconfig.plist
SmartSyncExplorerSwift/SmartSyncExplorerSwift.xcodeproj/project.pbxproj
SmartSyncExplorerSwift/SmartSyncExplorerSwift/AppDelegate.swift
SmartSyncExplorerSwift/SmartSyncExplorerSwift/Resources/bootconfig.plist
iOSIDPTemplate/Authenticator.xcodeproj/project.pbxproj
iOSIDPTemplate/Authenticator/AppDelegate.swift
iOSIDPTemplate/Authenticator/bootconfig.plist
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/bootconfig.plist
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj
iOSNativeTemplate/iOSNativeTemplate/AppDelegate.m
iOSNativeTemplate/iOSNativeTemplate/bootconfig.plist

All initializeSDK related changes in templates.

Refactored code to use SDK initialize instead of launch

---

BaristaSwift/Common/Common/Base/Store.swift
BaristaSwift/Common/Common/Store/AccountStore.swift
BaristaSwift/Common/Common/Store/FavoritesStore.swift
BaristaSwift/Common/Common/Store/OpportunityStore.swift
BaristaSwift/Common/Common/Store/OrderItemStore.swift
BaristaSwift/Common/Common/Store/OrderStore.swift
BaristaSwift/Common/Common/Store/PricebookStore.swift
BaristaSwift/Common/Common/Store/ProductOptionStore.swift
BaristaSwift/Common/Common/Store/ProductStore.swift
BaristaSwift/Common/Common/Store/QuoteLineGroupStore.swift
BaristaSwift/Common/Common/Store/QuoteLineItemStore.swift
BaristaSwift/Common/Common/Store/QuoteStore.swift
BaristaSwift/Common/Common/Store/UserStore.swift
BaristaSwift/Consumer/Consumer/ViewController/AccountViewController.swift
SmartSyncExplorerSwift/SmartSyncExplorerSwift/SObjects/SObjects.swift
SmartSyncExplorerSwift/SmartSyncExplorerSwift/ViewControllers/RootViewController.swift
iOSIDPTemplate/Authenticator/AppDelegate.swift

Merge only after https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2634
To test before that, make sure to edit the `package.json` files, replace: 
`"SalesforceMobileSDK-iOS": "https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git#dev"`
with: 
`"SalesforceMobileSDK-iOS": "https://github.com/wmathurin/SalesforceMobileSDK-iOS.git#swift"`

Fixing swift templates to use new APIs

---

SmartSyncExplorerSwift/Podfile
SmartSyncExplorerSwift/SmartSyncExplorerSwift.xcodeproj/project.pbxproj
SmartSyncExplorerSwift/SmartSyncExplorerSwift/AppDelegate.swift
SmartSyncExplorerSwift/SmartSyncExplorerSwift/SObjects/SObjects.swift
SmartSyncExplorerSwift/SmartSyncExplorerSwift/ViewControllers/RootViewController.swift

Removed dependency on  promises.

Refactored SmartSyncExplorer Swift template to remove promises

---

BaristaSwift/Common/Common/Base/Store.swift
BaristaSwift/Common/Common/Helper/ImageCache.swift
BaristaSwift/Common/Common/Helper/UIImageViewExtension.swift
BaristaSwift/Common/Common/Store/AccountStore.swift
BaristaSwift/Common/Common/Store/FavoritesStore.swift
BaristaSwift/Common/Common/Store/LocalCartStore.swift
BaristaSwift/Common/Common/Store/LocalOrderStore.swift
BaristaSwift/Common/Common/Store/OpportunityStore.swift
BaristaSwift/Common/Common/Store/OrderItemStore.swift
BaristaSwift/Common/Common/Store/OrderStore.swift
BaristaSwift/Common/Common/Store/PricebookStore.swift
BaristaSwift/Common/Common/Store/ProductOptionStore.swift
BaristaSwift/Common/Common/Store/ProductStore.swift
BaristaSwift/Common/Common/Store/QuoteLineGroupStore.swift
BaristaSwift/Common/Common/Store/QuoteLineItemStore.swift
BaristaSwift/Common/Common/Store/QuoteStore.swift
BaristaSwift/Common/Common/Store/UserStore.swift
BaristaSwift/Consumer/Consumer.xcodeproj/project.pbxproj
BaristaSwift/Consumer/Consumer/AppDelegate.swift
BaristaSwift/Consumer/Consumer/ViewController/FeaturedViewController.swift
BaristaSwift/Podfile
BaristaSwift/Provider/Provider.xcodeproj/project.pbxproj
BaristaSwift/Provider/Provider/AppDelegate.swift

Now pointing to this [location](https://github.com/trooper2013/SalesforceMobileSDK-iOS-Promises)

Changed PromiseKit wrapper dependency

---

AndroidIDPTemplate/app/AndroidManifest.xml
AndroidIDPTemplate/app/build.gradle
AndroidIDPTemplate/build.gradle
AndroidIDPTemplate/gradle.properties
AndroidIDPTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeKotlinTemplate/app/AndroidManifest.xml
AndroidNativeKotlinTemplate/app/build.gradle
AndroidNativeKotlinTemplate/build.gradle
AndroidNativeKotlinTemplate/gradle.properties
AndroidNativeKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeTemplate/app/AndroidManifest.xml
AndroidNativeTemplate/app/build.gradle
AndroidNativeTemplate/build.gradle
AndroidNativeTemplate/gradle.properties
AndroidNativeTemplate/gradle/wrapper/gradle-wrapper.properties
ReactNativeTemplate/android/app/build.gradle
ReactNativeTemplate/android/app/src/main/AndroidManifest.xml
ReactNativeTemplate/android/build.gradle
ReactNativeTemplate/android/gradle/wrapper/gradle-wrapper.properties
SmartSyncExplorerReactNative/android/app/build.gradle
SmartSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
SmartSyncExplorerReactNative/android/build.gradle
SmartSyncExplorerReactNative/android/gradle/wrapper/gradle-wrapper.properties

Adding support for Android Studio 3.2

---

AndroidIDPTemplate/build.gradle
AndroidIDPTemplate/gradle.properties
AndroidNativeKotlinTemplate/build.gradle
AndroidNativeKotlinTemplate/gradle.properties
AndroidNativeTemplate/build.gradle
AndroidNativeTemplate/gradle.properties
ReactNativeTemplate/android/build.gradle
ReactNativeTemplate/android/gradle.properties
SmartSyncExplorerReactNative/android/build.gradle
SmartSyncExplorerReactNative/android/gradle.properties

@wmathurin This did it for the native template.

Fixing compilation for templates

---

BaristaSwift/Consumer/Consumer.xcodeproj/project.pbxproj
BaristaSwift/Podfile
BaristaSwift/Provider/Provider.xcodeproj/project.pbxproj
ReactNativeTemplate/ios/Podfile
SmartSyncExplorerReactNative/ios/Podfile
SmartSyncExplorerSwift/Podfile
SmartSyncExplorerSwift/SmartSyncExplorerSwift.xcodeproj/project.pbxproj
SmartSyncExplorerSwift/SmartSyncExplorerSwift/ViewControllers/RootViewController.swift
iOSIDPTemplate/Authenticator.xcodeproj/project.pbxproj
iOSIDPTemplate/Authenticator/RootViewController.swift
iOSIDPTemplate/Podfile
iOSNativeSwiftTemplate/Podfile
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/RootViewController.swift
iOSNativeTemplate/Podfile
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj
iOSNativeTemplate/iOSNativeTemplate/RootViewController.m

Everything building/running (except for Barista, but I'm moving it out in the next PR).

Updates for logger changes

---

ReactNativeTemplate/ios/Podfile
SmartSyncExplorerReactNative/ios/Podfile
SmartSyncExplorerSwift/Podfile
iOSIDPTemplate/Podfile
iOSNativeSwiftTemplate/Podfile
iOSNativeTemplate/Podfile

FMDB fixed the issue that required that work around and forced us to stay on cocoapod 1.4

Podfile work around is no longer needed

---

iOSIDPTemplate/Authenticator/AppDelegate.swift
iOSIDPTemplate/Authenticator/MainViewController.swift
iOSIDPTemplate/Authenticator/PermissionsNavViewController.swift
iOSIDPTemplate/Authenticator/PermissionsViewController.swift
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate/AppDelegate.swift

Some swift 4.2 changes and cleanup commented code.

Cleaning up template code

---

ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
SmartSyncExplorerReactNative/ios/SmartSyncExplorerReactNative.xcodeproj/project.pbxproj
SmartSyncExplorerSwift/SmartSyncExplorerSwift.xcodeproj/project.pbxproj
iOSNativeSwiftTemplate/iOSNativeSwiftTemplate.xcodeproj/project.pbxproj
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj

Removes the old Launch Image reference from Assets.

Removes the old Launch Image reference from Assets.

---

HybridLocalTemplate/index.html

Safe area inset for hybrid local template app

---

AndroidIDPTemplate/app/AndroidManifest.xml
AndroidIDPTemplate/app/res/layout/main.xml
AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainActivity.kt
AndroidNativeKotlinTemplate/app/AndroidManifest.xml
AndroidNativeKotlinTemplate/app/res/layout/header.xml
AndroidNativeKotlinTemplate/app/res/layout/main.xml
AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainActivity.kt
AndroidNativeTemplate/app/AndroidManifest.xml
AndroidNativeTemplate/app/res/layout/header.xml
AndroidNativeTemplate/app/res/layout/main.xml
AndroidNativeTemplate/app/src/com/salesforce/androidnativetemplate/MainActivity.java

Add dark theme to native android templates.

Android Dark Theme

---

MobileSyncExplorerReactNative/ios/MobileSyncExplorerReactNative.xcodeproj/project.pbxproj
MobileSyncExplorerReactNative/ios/Podfile
MobileSyncExplorerReactNative/js/SearchScreen.js
MobileSyncExplorerReactNative/package.json
ReactNativeTemplate/ios/Podfile
ReactNativeTemplate/ios/ReactNativeTemplate.xcodeproj/project.pbxproj
ReactNativeTemplate/package.json

Was able to run the two template apps on iOS and Android.

Move to React Native 0.61

---

MobileSyncExplorerReactNative/template.js
MobileSyncExplorerSwift/template.js
ReactNativeTemplate/template.js
iOS13NativeSwiftTemplate/template.js
iOS13OfflineNativeSwiftTemplate/iOS13OfflineNativeSwiftTemplate/SceneDelegate.swift
iOS13OfflineNativeSwiftTemplate/template.js
iOSIDPTemplate/template.js
iOSNativeSwiftTemplate/template.js
iOSNativeTemplate/template.js

Also cleaning up template.js files

Store and syncs need to be configured during a user switch also

---

MobileSyncExplorerReactNative/ios/MobileSyncExplorerReactNative/Info.plist
ReactNativeTemplate/ios/ReactNativeTemplate/Info.plist

Reverts forcedotcom/SalesforceMobileSDK-Templates#229

Revert "Disable dark mode for iOS react apps"

---

iOS13OfflineNativeSwiftTemplate/iOS13OfflineNativeSwiftTemplate/ContactListModel.swift
iOS13OfflineNativeSwiftTemplate/iOS13OfflineNativeSwiftTemplate/ContactListView.swift
iOS13OfflineNativeSwiftTemplate/iOS13OfflineNativeSwiftTemplate/userstore.json
iOS13OfflineNativeSwiftTemplate/iOS13OfflineNativeSwiftTemplate/usersyncs.json
iOSNativeTemplate/iOSNativeTemplate.xcodeproj/project.pbxproj

- pulling contacts instead of users
- added subscriber in fetchContacts

Fixes for iOS 13 offline templates

---

iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/AccountsListView.swift
iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/ContactDetailsView.swift
iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/ContactsForAccountListView.swift

Original commit https://github.com/codefriar/SwiftUICombineAndSDK/commit/a4ee1e5e265d5ac60a36ea5a12d71de0a9b2713d

Updating preview structs 

---

MobileSyncExplorerReactNative/js/SearchScreen.js

Logout button in sample app doesn't work due to missing import

fixes logout in sample app

---

iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/AccountsListModel.swift
iOS13NativeSwiftTemplate/iOS13NativeSwiftTemplate/ContactsForAccountModel.swift

Cancellables go out of scope hence prevents  updating of the models.

Fixing bug related to empty lists being shown for accounts

---

ReactNativeTemplate/ios/ReactNativeTemplate/AppDelegate.m

For https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/3225

Add push request to iOS React template

---

MobileSyncExplorerReactNative/template.js
MobileSyncExplorerSwift/template.js
ReactNativeDeferredTemplate/template.js
ReactNativeTemplate/template.js
ReactNativeTypeScriptTemplate/template.js
iOSIDPTemplate/template.js
iOSNativeSwiftEncryptedNotificationTemplate/template.js
iOSNativeSwiftTemplate/template.js
iOSNativeTemplate/template.js

Updating returned value from template.js which is used to produce the "Next steps" print out on the screen after running forceios, forcereact etc

Consumer key etc are not in AppDelegate.m/swift 

---

MobileSyncExplorerReactNative/ios/Podfile
ReactNativeDeferredTemplate/ios/Podfile
ReactNativeTemplate/ios/Podfile
ReactNativeTypeScriptTemplate/ios/Podfile

Using workaround suggested [here](https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-790498006)

Fixes for compilation errors of RN template on xcode 12

---

AndroidIDPTemplate/app/build.gradle
AndroidIDPTemplate/build.gradle
AndroidIDPTemplate/gradle.properties
AndroidNativeKotlinTemplate/app/build.gradle
AndroidNativeKotlinTemplate/build.gradle
AndroidNativeKotlinTemplate/gradle.properties
AndroidNativeTemplate/app/build.gradle
AndroidNativeTemplate/build.gradle
AndroidNativeTemplate/gradle.properties
MobileSyncExplorerReactNative/android/build.gradle
ReactNativeDeferredTemplate/android/build.gradle
ReactNativeTemplate/android/build.gradle
ReactNativeTypeScriptTemplate/android/build.gradle

- Bumping up target API version to `31`.
- Bumping up AGP version to `7.0.3`.

Adding Support for Android S

---

AndroidIDPTemplate/app/AndroidManifest.xml
AndroidNativeKotlinTemplate/app/AndroidManifest.xml
AndroidNativeTemplate/app/AndroidManifest.xml
MobileSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
ReactNativeDeferredTemplate/android/app/src/main/AndroidManifest.xml

Apps targeting API 31 require all activities need to be exported.

Fix all Android templates

---

MobileSyncExplorerReactNative/ios/Podfile
ReactNativeDeferredTemplate/ios/Podfile
ReactNativeTemplate/ios/Podfile
ReactNativeTypeScriptTemplate/ios/Podfile

To be aligned with RN template

Pod file changes

---

MobileSyncExplorerSwift/MobileSyncExplorerSwift.xcodeproj/project.pbxproj
MobileSyncExplorerSwift/MobileSyncExplorerSwift/AppDelegate.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/ContactDetailViewModel.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/ContactListViewModel.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/Helpers/ContactHelpers.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/Info.plist
MobileSyncExplorerSwift/MobileSyncExplorerSwift/MobileSyncExplorerSwift.entitlements
MobileSyncExplorerSwift/MobileSyncExplorerSwift/SObjects/SObjects.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/SceneDelegate.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/Views/ContactDetail.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/Views/ContactList.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/Views/NotificationList.swift
MobileSyncExplorerSwift/Podfile
MobileSyncExplorerSwift/RecentContacts/Assets.xcassets/AccentColor.colorset/Contents.json
MobileSyncExplorerSwift/RecentContacts/Assets.xcassets/AppIcon.appiconset/Contents.json
MobileSyncExplorerSwift/RecentContacts/Assets.xcassets/Contents.json
MobileSyncExplorerSwift/RecentContacts/Assets.xcassets/WidgetBackground.colorset/Contents.json
MobileSyncExplorerSwift/RecentContacts/Info.plist
MobileSyncExplorerSwift/RecentContacts/RecentContacts.swift
MobileSyncExplorerSwift/RecentContacts/RecentContactsWidget.swift
MobileSyncExplorerSwift/RecentContactsExtension.entitlements

https://user-images.githubusercontent.com/840431/152848237-de1fdab9-6a17-47f1-ae65-5542fccd9764.mov

Add recent contacts widget for MobileSyncExplorerSwift

---

AndroidIDPTemplate/app/build.gradle
AndroidIDPTemplate/build.gradle
AndroidIDPTemplate/gradle.properties
AndroidIDPTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeKotlinTemplate/app/build.gradle
AndroidNativeKotlinTemplate/build.gradle
AndroidNativeKotlinTemplate/gradle.properties
AndroidNativeKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeTemplate/app/build.gradle
AndroidNativeTemplate/build.gradle
AndroidNativeTemplate/gradle.properties
AndroidNativeTemplate/gradle/wrapper/gradle-wrapper.properties
MobileSyncExplorerKotlinTemplate/app/build.gradle
MobileSyncExplorerKotlinTemplate/build.gradle
MobileSyncExplorerKotlinTemplate/gradle.properties
MobileSyncExplorerKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
MobileSyncExplorerReactNative/android/build.gradle
MobileSyncExplorerReactNative/android/gradle.properties
MobileSyncExplorerReactNative/android/gradle/wrapper/gradle-wrapper.properties
ReactNativeDeferredTemplate/android/build.gradle
ReactNativeDeferredTemplate/android/gradle/wrapper/gradle-wrapper.properties
ReactNativeTemplate/android/build.gradle
ReactNativeTemplate/android/gradle/wrapper/gradle-wrapper.properties
ReactNativeTypeScriptTemplate/android/build.gradle
ReactNativeTypeScriptTemplate/android/gradle/wrapper/gradle-wrapper.properties

Add Kotlin Dependency and update Gradle

---

AndroidIDPTemplate/app/AndroidManifest.xml
AndroidIDPTemplate/app/res/values/bootconfig.xml
AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainActivity.kt
AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainApplication.kt
AndroidNativeKotlinTemplate/app/AndroidManifest.xml
AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainApplication.kt
AndroidNativeTemplate/app/AndroidManifest.xml
AndroidNativeTemplate/app/src/com/salesforce/androidnativetemplate/MainApplication.java
MobileSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
ReactNativeDeferredTemplate/android/app/src/main/AndroidManifest.xml
ReactNativeTemplate/android/app/src/main/AndroidManifest.xml
ReactNativeTypeScriptTemplate/android/app/src/main/AndroidManifest.xml

Update to Android IDP template (goes with https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2393)

Multi App SSO for Android

---

AndroidIDPTemplate/template.js
AndroidNativeKotlinTemplate/template.js
AndroidNativeTemplate/template.js
MobileSyncExplorerKotlinTemplate/template.js

Should fix generating apps with forcedroid.

Fixing template.js scripts

---

AndroidIDPTemplate/app/build.gradle.kts
AndroidIDPTemplate/install.js
AndroidIDPTemplate/package.json
AndroidIDPTemplate/settings.gradle.kts
AndroidNativeKotlinTemplate/app/build.gradle.kts
AndroidNativeKotlinTemplate/install.js
AndroidNativeKotlinTemplate/package.json
AndroidNativeKotlinTemplate/settings.gradle.kts
AndroidNativeTemplate/app/build.gradle.kts
AndroidNativeTemplate/install.js
AndroidNativeTemplate/package.json
AndroidNativeTemplate/settings.gradle.kts
HybridLocalTemplate/install.js
HybridLocalTemplate/package.json
HybridLocalTemplate/template.js
HybridLwcTemplate/install.js
HybridLwcTemplate/package.json
HybridLwcTemplate/template.js
HybridRemoteTemplate/install.js
HybridRemoteTemplate/package.json
HybridRemoteTemplate/template.js
MobileSyncExplorerKotlinTemplate/app/build.gradle.kts
MobileSyncExplorerKotlinTemplate/install.js
MobileSyncExplorerKotlinTemplate/package.json
MobileSyncExplorerKotlinTemplate/settings.gradle.kts
MobileSyncExplorerReactNative/package.json
ReactNativeDeferredTemplate/package.json
ReactNativeTemplate/package.json
ReactNativeTypeScriptTemplate/package.json
setversion.sh

🥁 _Ready For Review_ 🎸
This is a companion to https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/pull/626
This updates the hybrid templates to clone a copy of MSDK-Android for use in their composite build when the version is not a tagged release.

@W-14246983: [Android][Hybrid] Hybrid Templates Use Maven Central MSDK Dependencies By Default

---

AndroidIDPTemplate/app/AndroidManifest.xml
AndroidNativeKotlinTemplate/app/AndroidManifest.xml
AndroidNativeTemplate/app/AndroidManifest.xml
MobileSyncExplorerReactNative/android/app/src/main/AndroidManifest.xml
ReactNativeDeferredTemplate/android/app/src/main/AndroidManifest.xml
ReactNativeTemplate/android/app/src/main/AndroidManifest.xml
ReactNativeTypeScriptTemplate/android/app/src/main/AndroidManifest.xml

Relies on https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2484

Replace singleInstance launch mode with singleTop for LoginActivity.

---

AndroidIDPTemplate/app/res/values/bootconfig.xml
AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainApplication.kt
AndroidNativeKotlinTemplate/app/res/values/bootconfig.xml
AndroidNativeKotlinTemplate/app/src/com/salesforce/androidnativekotlintemplate/MainApplication.kt
AndroidNativeTemplate/app/res/values/bootconfig.xml
AndroidNativeTemplate/app/src/com/salesforce/androidnativetemplate/MainApplication.java
HybridLocalTemplate/bootconfig.json
HybridLwcTemplate/bootconfig.json
HybridRemoteTemplate/bootconfig.json
MobileSyncExplorerKotlinTemplate/app/src/main/res/values/bootconfig.xml
MobileSyncExplorerReactNative/android/app/src/main/java/com/salesforce/samples/mobilesyncexplorerreactnative/MainApplication.java
MobileSyncExplorerReactNative/android/app/src/main/res/values/bootconfig.xml
ReactNativeDeferredTemplate/android/app/src/main/java/com/salesforce/reactnativedeferredtemplate/MainApplication.java
ReactNativeDeferredTemplate/android/app/src/main/res/values/bootconfig.xml
ReactNativeTemplate/android/app/src/main/java/com/salesforce/reactnativetemplate/MainApplication.java
ReactNativeTemplate/android/app/src/main/res/values/bootconfig.xml
ReactNativeTypeScriptTemplate/android/app/src/main/java/com/salesforce/reactnativetypescripttemplate/MainApplication.java
ReactNativeTypeScriptTemplate/android/app/src/main/res/values/bootconfig.xml

This PR requires: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2486

Update templates for Firebase 23.3.1.

---

AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainApplication.kt

🎸 _Ready For Review_ 🥁
This is a companion to 👉🏻 https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2482

@W-13668007: [Android][Modernization] Remove MSDK Android MobileSyncExplorer Sample App In Favor of MSDK Templates Kotlin Compose Version

---

AndroidIDPTemplate/app/build.gradle.kts
AndroidNativeKotlinTemplate/app/build.gradle.kts
AndroidNativeTemplate/app/build.gradle.kts

SalesforceSDKManager's getBuildConfigValue looks for it

Generating BuildConfig

---

AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/NativeLogin.kt
AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/NativeLoginViewModel.kt

🎸 _Ready For Review_ 🥁
Here's the sample app update to match https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2567

@W-15316991: [Android] Update native login sample app to include Forgot Password flow

---

AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/MainApplication.kt
AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/NativeLogin.kt
AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/NativeLoginViewModel.kt
AndroidNativeLoginTemplate/settings.gradle.kts

🎸 _Review For Review!_ 🥁
Now we have headless registration via the Salesforce Identity API as well.  This will look very familiar to reviewers of other recent headless identity flow pull requests.

@W-15316975: [Android] Update native login sample app to include User Registration flow

---

MobileSyncExplorerSwift/MobileSyncExplorerSwift/ContactDetailViewModel.swift
MobileSyncExplorerSwift/MobileSyncExplorerSwift/Views/ContactDetail.swift

Delete Button Bug Fix

---

AndroidIDPTemplate/build.gradle.kts
AndroidIDPTemplate/buildSrc/build.gradle.kts
AndroidIDPTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeKotlinTemplate/build.gradle.kts
AndroidNativeKotlinTemplate/buildSrc/build.gradle.kts
AndroidNativeKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeLoginTemplate/build.gradle.kts
AndroidNativeLoginTemplate/buildSrc/build.gradle.kts
AndroidNativeLoginTemplate/gradle/wrapper/gradle-wrapper.properties
AndroidNativeTemplate/build.gradle.kts
AndroidNativeTemplate/buildSrc/build.gradle.kts
AndroidNativeTemplate/gradle/wrapper/gradle-wrapper.properties
MobileSyncExplorerKotlinTemplate/build.gradle.kts
MobileSyncExplorerKotlinTemplate/buildSrc/build.gradle.kts
MobileSyncExplorerKotlinTemplate/gradle/wrapper/gradle-wrapper.properties
MobileSyncExplorerReactNative/android/build.gradle
MobileSyncExplorerReactNative/android/gradle/wrapper/gradle-wrapper.properties
ReactNativeDeferredTemplate/android/build.gradle
ReactNativeDeferredTemplate/android/gradle/wrapper/gradle-wrapper.properties
ReactNativeTemplate/android/build.gradle
ReactNativeTemplate/android/gradle/wrapper/gradle-wrapper.properties
ReactNativeTypeScriptTemplate/android/build.gradle
ReactNativeTypeScriptTemplate/android/gradle/wrapper/gradle-wrapper.properties

Tested from SalesforceMobileSDK-Package
- pointed `templatesRepoUri` in `shared/constants.js` to `https://github.com/wmathurin/SalesforceMobileSDK-Templates#dev`
- ran ./test/test_force.js --cli=forcedroid,forcereact --os=android

Bumping gradle to 8.5

---

AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/NativeLogin.kt

🥁 _Ready For Review!_ 🎸
This corrects the status bar, navigation bar and IME padding for the Android native login template app.  Previously, the taller registration form was scrolling the focused field vertically up and out of view on focus.  Now, all of the layouts will adjust gracefully to these three layout topics.
I gave @brandonpage a demonstration and a screen-share walk-through as well so he could closely review how this matches with his original layout.

@W-15811064: [MSDK Android Templates] Native Login Template Scrolls Registration Text Fields Out Of View On Focus

---

AndroidNativeKotlinTemplate/app/build.gradle.kts
AndroidNativeKotlinTemplate/app/src/main/AndroidManifest.xml
AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/MainActivity.kt
AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/QrCodeEnabledLoginActivity.kt
AndroidNativeKotlinTemplate/app/src/main/res/layout/sf__login.xml
AndroidNativeKotlinTemplate/app/src/main/res/values/strings.xml
AndroidNativeKotlinTemplate/build.gradle.kts
AndroidNativeKotlinTemplate/buildSrc/build.gradle.kts

🥁 _*Ready For Review!*_ 🎸
This is a companion to https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2625

@W-16336722: [MSDK Android] QR Code Log In Using External QR Code Reader Does Not Display Main Activity

---

AndroidNativeKotlinTemplate/template.js

🎸 _*Ready For Review*_ 🥁
This simple update adds new template files to the script so they're not skipped during the package rename phase.

@W-16814802: [iOS] Add Deep Link From External QR Code Reader To iOS Native Swift Template QR Code Login (Update template.js)

---

iOSNativeSwiftEncryptedNotificationTemplate/EncryptedNotificationTemplate/RootViewController.swift

Updated to use modern API request.  The new API uses async/await design.

@W-17669889 Using modern API for sending request

---

AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/QrCodeEnabledLoginActivity.kt

🎸 *_Ready For Review_* 🥁
This is a counterpart to https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2668

@W-17411362: LoginActivity Fit and Finish

---

AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/MainActivity.kt

W-17875964: [MSDK Android] Log In Via QR Code Navigates To Authenticated Activity, Returns To Log In After App Restart

---

AndroidIDPTemplate/app/src/main/java/com/salesforce/samples/salesforceandroididptemplateapp/MainActivity.kt
AndroidNativeKotlinTemplate/app/src/main/java/com/salesforce/androidnativekotlintemplate/MainActivity.kt
AndroidNativeKotlinTemplate/app/src/main/res/layout/main.xml
AndroidNativeLoginTemplate/app/src/main/java/com/salesforce/androidnativelogintemplate/MainActivity.kt
AndroidNativeTemplate/app/src/main/java/com/salesforce/androidnativetemplate/MainActivity.java
AndroidNativeTemplate/app/src/main/res/layout/main.xml

@W-17875985: [MSDK Android] Template App Styles And Themes Changed With MSDK 13
